[package]
name = "bg-maker"
version = "0.0.1"
edition = "2018"

[dependencies]
iced = { version = "0.13.1", features = [ "debug", "canvas" ] }
windows = { version = "0.61.1", features = [ "Win32_System_Com", "Win32_UI_Shell" ] }
